//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Update-AssemblyInfo.ps1
//
//     Changes to this file must be made in that script
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("9.0.0.0")]
[assembly: AssemblyFileVersionAttribute("9.0.0.0")]
[assembly: AssemblyCopyrightAttribute("© Relativity")]
[assembly: AssemblyCompanyAttribute("Relativity ODA LLC")]